### ISSUE TITLE
[BUG] Loading a codeblock into editor, try to highlight some code, and it errors out in console but not crashing.

### ISSUE THREAD

**Issue by trancethehuman** [Darginec05/Editor-Yopta#318]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The error message: `Error: Cannot find a descendant at path [0] in node: {"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}`

### Steps to Reproduce

1. Load a codeblock element
2. Try to highlight some text in it first-thing.

### Environment

- OS: MacOS
- Browser: Chrome

### Screenshots

https://github.com/user-attachments/assets/e89cb61d-61ac-4c71-aa15-4cf770cf64ab

### Do you want to work on this issue?

No

**Comment by Darginec05** [comment]
Could you recheck it please with v4.9.0? 
It seems fixed in 4.9.0

Reopen issue if the bug still appears
